# ---------------------------------------------------------------
# Theme default settings
# 主题默认设置
# ---------------------------------------------------------------

# menu setting | format = titleName: linkUrl
menu:
  PAGE: /page

# Enable table of content
TOC: false

# Home page first post default cover image, default use cover
welcome_cover: /img/cover.jpg

# Article default cover image
cover: /img/welcome-cover.jpg

# Disable default scrollbar
scrollbar: true

# Website keywords used for SEO
keywords: TriDiamond Obsidian

# Website slogans
descriptionOne: "Think like an artist, develop like an artisan"
descriptionTwo: "艺术家思维去思考问题，工匠创造精神去开发"

# If you use google analytics, please fill in the ID
google_analytics:

# Website favicon
favicon: /img/favicon.png

# rss file
rss: atom.xml

# ---------------------------------------------------------------
# Article Music settings
# ---------------------------------------------------------------

# Auto play article audio
autoplay: false

# default mp3 file
mp3: 
  - statics/chengdu.mp3

# ---------------------------------------------------------------
# Plugins
# ---------------------------------------------------------------

# Gitalk comment plugin
# see https://github.com/gitalk/gitalk
gitalk:
  # 是否自动展开评论框
  autoExpand: false
  # 应用编号
  clientID: ''
  # 应用秘钥
  clientSecret: ''
  # issue仓库名
  repo: ''
  # Github名
  owner: ''
  # Github名
  admin: ['']
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction

# Enable symbols-count-time plugin
# see https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  enable: true
  wordCount: true
  readCount: true
  awl: 4
  wpm: 275
  suffix: mins.

# Enable html truncate
# see https://github.com/TriDiamond/hexo-html-truncate
html_truncate:
  enable: true
  # Characters kept for posts
  postLength: 250
  # Characters kept for cover posts
  coverLength: 100
  ellipsis: '...'
  # Excluding html tags
  excludes: ['img']
  # Characters count including white spaces
  keepWhitespaces: true
  # Reserving the last complete word, without breaking the word
  reserveLastWord: true

#! ---------------------------------------------------------------
##! Obsidian theme use manual highlight.js
##! To maintain the code block css display properly
##! please keep this as off!!
#! ---------------------------------------------------------------
highlight:
  enable: false
  line_number: true
  auto_detect: true
  tab_replace:
